language: ruby
rvm:
  - 2.3.0
script: bundle exec middleman build
sudo: false
deploy:
  provider: s3
  access_key_id: AKIAJ2E6H43DEGK4QS6Q
  secret_access_key:
    secure: kdLdqb8Rhr7WRqjpL79Cgvz4ulkw6GrLh7rkkgUx8XQtQLG17nqfb7Z8XXtb3PSYHyAVsRk84PLRg1RVpu6AS5Z829vQb0nGlqv4WUatBzCj0yh/SvikdSkN0+MeqTYRsoIa3GN5IDNz+UxKpOaDa3Z9BFjQFPWqvg98Z0VTZrV84jbl1djqQqTbvkUc+Q1Oi1Xajfm76wlRqMzbbkY9GKDkdQh8StsQY+txkkCpekGNWwg4SBLmQG3NGTeqn9HSKE7WfDsZWKDgAN8VPcfUzUYVersK6EbqJZBIZ2vtQO7CGYx40ncZEjCtNkEf0i1mNdYphSdIqhUyA2m0ERSITrorJGOMm8KQP/vCmyp2dum/NbPejMdN9xpVKPKGSg4xBDtMehyfSPGnCjLQPJILloVSNiy2hdmvsU2YQy94n2NGGRUe9HiFLxErsdfCNcKqw562SERWwLsnhJjUpURf+9OVgmx5iny0GqeNUHnkm61Ax+FQQFebqGd0QedEO8KMtW1LPGLVc8Knz1cq6WzZ/YP2lslx6HUzi6hI83ZYSc9rRFwNohJ80FdHtyhQ1AxyIzU8zuMNMdGSZPU9sJndf++Q+G4ua7dXmQZd3DyAFAOhdCjXg93IzdaxcZz10b6TlrFVigVqVTffqF1g6q+GDyUVTNbwYliR6cLGSuAtNgc=
  bucket: waldowski.me
  local-dir: build
  acl: public_read
  skip_cleanup: true
  cache_control: "max-age=31536000,public,must-revalidate,proxy-revalidate"
  on:
    repo: zwaldowski/waldowski.me
    tags: true
