# Site settings
title: Zach Waldowski
author: Zachary Waldowski
email: zach@waldowski.me
description: >
  App developer. I do the best imitation of myself.
url: "https://zwaldowski.github.io"

# Build settings
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
exclude:
  - Gemfile
  - Gemfile.lock
  - Project.sublime-project
  - Project.sublime-workspace
  - node_modules
